In [8]:
import pandas as pd

In [9]:
df = pd.read_excel('../data_processed/conflict.xlsx', index_col=False)

In [10]:
df.head(5)

,time,conflict,opposing,neutral,opp,govt,target,died,endate,start,...,govopp,intense,avemnth,milint,econint,govmil,govecon,oppmil,neutmil,neutecon
0,1.0,600,0,0,0,0,0,0,1999-06-01,1998-01-01,...,0,1515.152,9.9,0,0,0,0,0,0,0
1,2.0,600,0,0,0,0,0,0,1999-06-01,1998-02-01,...,0,1515.152,9.9,0,0,0,0,0,0,0
2,3.0,600,0,0,0,0,0,0,1999-06-01,1998-03-01,...,0,1515.152,9.9,0,0,0,0,0,0,0
3,4.0,600,0,0,0,0,0,0,1999-06-01,1998-04-01,...,0,1515.152,9.9,0,0,0,0,0,0,0
4,5.0,600,0,0,1,0,2,0,1999-06-01,1998-05-01,...,1,1515.152,9.9,0,1,0,0,0,0,0

In [11]:
df.columns

Index(['time', 'conflict', 'opposing', 'neutral', 'opp', 'govt', 'target',
       'died', 'endate', 'start', '_yearmo', 'ccode', 'sizeopp', 'group1',
       'group2', 'group3', 'group4', 'refugees', 'coldwar', 'typeIden',
       'fatal', 'interven', 'Linked', 'dayint', 'yrintv', 'mnthint', 'thrdpar',
       'military', 'clash', 'economic', 'ethnic_', 'ethn_nam', '_merge', '_d',
       '_t', '_t0', 'CWint', 'troops', 'navy', 'equip', 'intel', 'airforce',
       'grant', 'loan', 'aid', 'credit', 'relief', 'sanction', 'force',
       'avefrac', 'ideology', 'religion', 'ethnic', 'timing', 'timeforc',
       'ethnorel', 'forcegov', 'forceopp', 'majmin', 'timegov', 'Intorg',
       'govopp', 'intense', 'avemnth', 'milint', 'econint', 'govmil',
       'govecon', 'oppmil', 'neutmil', 'neutecon'],
      dtype='object')

In [12]:
print(df.head())

   time  conflict  opposing  neutral  opp  govt  target  died     endate  \
0   1.0       600         0        0    0     0       0     0 1999-06-01
1   2.0       600         0        0    0     0       0     0 1999-06-01
2   3.0       600         0        0    0     0       0     0 1999-06-01
3   4.0       600         0        0    0     0       0     0 1999-06-01
4   5.0       600         0        0    1     0       2     0 1999-06-01

       start  ...  govopp   intense  avemnth milint econint govmil govecon  \
0 1998-01-01  ...       0  1515.152      9.9      0       0      0       0
1 1998-02-01  ...       0  1515.152      9.9      0       0      0       0
2 1998-03-01  ...       0  1515.152      9.9      0       0      0       0
3 1998-04-01  ...       0  1515.152      9.9      0       0      0       0
4 1998-05-01  ...       1  1515.152      9.9      0       1      0       0

   oppmil  neutmil  neutecon
0       0        0         0
1       0        0         0
2       0        0         0
3       0        0         0
4       0        0         0

[5 rows x 71 columns]

In [14]:
len(df['ccode'].unique())

76

In [16]:
len(df['conflict'].unique())

150

In [19]:
len(df['yrintv'].unique())

57

In [21]:


# specify the conflict you are interested in
conflict_name = df['conflict']

# filter the dataframe to only include rows where the 'war' column matches the conflict name
conflict_df = df[df['conflict'] == conflict_name]

# extract the unique values in the 'code' column of the filtered dataframe
code_of_war = conflict_df['ccode'].unique()

# print the code(s) of war that belong to the conflict
print(code_of_war)

[345 404 516 484 350 710 145 150 820 678  94 100 775 850 840  90 750 310
 660  40 645 817 530 812 615 625 517 352 483  42 800 500 475 230 698 811
 200 663 560 770 780 771 552 435 600 540 490 700 630  93  92 541 420 135
 520  55 130 680 450 360 436 432 372 522 365 373 640 346 359 501 702 651
  70 679 451 790]

In [27]:

# get the unique conflict names in the 'conflict' column
conflict_names = df['conflict'].unique()

# loop through the conflict names and print the corresponding ccode values
for conflict in conflict_names:
    conflict_codes = df.loc[df['conflict'] == conflict, 'ccode'].unique()
    print(f'Conflict: {conflict}')
    print(f'CCodes: {conflict_codes}')

Conflict: 600
CCodes: [345]
Conflict: 605
CCodes: [404]
Conflict: 610
CCodes: [516]
Conflict: 615
CCodes: [484]
Conflict: 620
CCodes: [484]
Conflict: 630
CCodes: [484]
Conflict: 781
CCodes: [350]
Conflict: 784
CCodes: [710]
Conflict: 785
CCodes: [145]
Conflict: 787
CCodes: [150]
Conflict: 788
CCodes: [710]
Conflict: 789
CCodes: [820]
Conflict: 790
CCodes: [678]
Conflict: 793
CCodes: [94]
Conflict: 796
CCodes: [100]
Conflict: 799
CCodes: [775]
Conflict: 802
CCodes: [100]
Conflict: 805
CCodes: [850]
Conflict: 808
CCodes: [840]
Conflict: 814
CCodes: [850]
Conflict: 817
CCodes: [90]
Conflict: 818
CCodes: [750]
Conflict: 822
CCodes: [310]
Conflict: 823
CCodes: [850]
Conflict: 826
CCodes: [660]
Conflict: 829
CCodes: [40]
Conflict: 830
CCodes: [710]
Conflict: 832
CCodes: [645]
Conflict: 835
CCodes: [817]
Conflict: 838
CCodes: [484]
Conflict: 840
CCodes: [530]
Conflict: 841
CCodes: [812]
Conflict: 842
CCodes: [645]
Conflict: 844
CCodes: [615]
Conflict: 845
CCodes: [530]
Conflict: 847
CCodes: [678]
Conflict: 850
CCodes: [812]
Conflict: 853
CCodes: [625]
Conflict: 855
CCodes: [517]
Conflict: 857
CCodes: [352]
Conflict: 858
CCodes: [483]
Conflict: 859
CCodes: [42]
Conflict: 860
CCodes: [850]
Conflict: 861
CCodes: [800]
Conflict: 862
CCodes: [500]
Conflict: 863
CCodes: [90]
Conflict: 864
CCodes: [475]
Conflict: 865
CCodes: [230]
Conflict: 866
CCodes: [484]
Conflict: 868
CCodes: [475]
Conflict: 869
CCodes: [775]
Conflict: 870
CCodes: [698]
Conflict: 871
CCodes: [811]
Conflict: 872
CCodes: [200]
Conflict: 874
CCodes: [663]
Conflict: 878
CCodes: [560]
Conflict: 880
CCodes: [770]
Conflict: 881
CCodes: [500]
Conflict: 882
CCodes: [660]
Conflict: 883
CCodes: [780]
Conflict: 884
CCodes: [771]
Conflict: 886
CCodes: [516]
Conflict: 887
CCodes: [840]
Conflict: 888
CCodes: [840]
Conflict: 889
CCodes: [552]
Conflict: 890
CCodes: [770]
Conflict: 891
CCodes: [645]
Conflict: 892
CCodes: [352]
Conflict: 893
CCodes: [435]
Conflict: 894
CCodes: [600]
Conflict: 895
CCodes: [850]
Conflict: 896
CCodes: [850]
Conflict: 897
CCodes: [540]
Conflict: 898
CCodes: [530]
Conflict: 899
CCodes: [490]
Conflict: 901
CCodes: [700]
Conflict: 902
CCodes: [490]
Conflict: 903
CCodes: [483]
Conflict: 904
CCodes: [630]
Conflict: 907
CCodes: [93]
Conflict: 908
CCodes: [811]
Conflict: 910
CCodes: [92]
Conflict: 913
CCodes: [541]
Conflict: 917
CCodes: [475]
Conflict: 918
CCodes: [710]
Conflict: 919
CCodes: [500]
Conflict: 920
CCodes: [552]
Conflict: 922
CCodes: [630]
Conflict: 923
CCodes: [420]
Conflict: 925
CCodes: [135]
Conflict: 928
CCodes: [93]
Conflict: 930
CCodes: [780]
Conflict: 931
CCodes: [520]
Conflict: 933
CCodes: [775]
Conflict: 934
CCodes: [483]
Conflict: 935
CCodes: [55]
Conflict: 936
CCodes: [100]
Conflict: 937
CCodes: [625]
Conflict: 938
CCodes: [130]
Conflict: 939
CCodes: [475]
Conflict: 940
CCodes: [475]
Conflict: 941
CCodes: [645]
Conflict: 942
CCodes: [750]
Conflict: 943
CCodes: [680]
Conflict: 944
CCodes: [780]
Conflict: 945
CCodes: [500]
Conflict: 946
CCodes: [516]
Conflict: 947
CCodes: [750]
Conflict: 948
CCodes: [530]
Conflict: 949
CCodes: [450]
Conflict: 950
CCodes: [360]
Conflict: 952
CCodes: [517]
Conflict: 953
CCodes: [436]
Conflict: 954
CCodes: [432]
Conflict: 955
CCodes: [560]
Conflict: 956
CCodes: [372]
Conflict: 957
CCodes: [522]
Conflict: 961
CCodes: [365]
Conflict: 962
CCodes: [373]
Conflict: 963
CCodes: [630]
Conflict: 964
CCodes: [345]
Conflict: 966
CCodes: [520]
Conflict: 967
CCodes: [640]
Conflict: 970
CCodes: [516]
Conflict: 971
CCodes: [645]
Conflict: 972
CCodes: [490]
Conflict: 973
CCodes: [346]
Conflict: 974
CCodes: [359]
Conflict: 975
CCodes: [501]
Conflict: 976
CCodes: [702]
Conflict: 977
CCodes: [700]
Conflict: 978
CCodes: [651]
Conflict: 979
CCodes: [450]
Conflict: 981
CCodes: [530]
Conflict: 982
CCodes: [540]
Conflict: 983
CCodes: [516]
Conflict: 984
CCodes: [615]
Conflict: 985
CCodes: [70]
Conflict: 986
CCodes: [679]
Conflict: 988
CCodes: [365]
Conflict: 989
CCodes: [483]
Conflict: 991
CCodes: [811]
Conflict: 992
CCodes: [372]
Conflict: 993
CCodes: [372]
Conflict: 994
CCodes: [750]
Conflict: 995
CCodes: [500]
Conflict: 996
CCodes: [451]
Conflict: 997
CCodes: [450]
Conflict: 998
CCodes: [771]
Conflict: 999
CCodes: [790]

In [31]:


# get the unique conflict names in the 'conflict' column
conflict_names = df['conflict'].unique()

# create an empty list to store the results
results = []

# loop through the conflict names and append the corresponding ccode values to the results list
for conflict in conflict_names:
    conflict_codes = df.loc[df['conflict'] == conflict, 'ccode'].unique()
    ccode_str = ', '.join(str(c) for c in conflict_codes)
    results.append({'Conflict': conflict, 'CCodes': ccode_str})

# create a new dataframe from the results list and display it
results_df = pd.DataFrame(results)
results_df.head()
results_df.to_excel('../data_processed/conflict_code.xlsx')

In [32]:
df.columns

Index(['time', 'conflict', 'opposing', 'neutral', 'opp', 'govt', 'target',
       'died', 'endate', 'start', '_yearmo', 'ccode', 'sizeopp', 'group1',
       'group2', 'group3', 'group4', 'refugees', 'coldwar', 'typeIden',
       'fatal', 'interven', 'Linked', 'dayint', 'yrintv', 'mnthint', 'thrdpar',
       'military', 'clash', 'economic', 'ethnic_', 'ethn_nam', '_merge', '_d',
       '_t', '_t0', 'CWint', 'troops', 'navy', 'equip', 'intel', 'airforce',
       'grant', 'loan', 'aid', 'credit', 'relief', 'sanction', 'force',
       'avefrac', 'ideology', 'religion', 'ethnic', 'timing', 'timeforc',
       'ethnorel', 'forcegov', 'forceopp', 'majmin', 'timegov', 'Intorg',
       'govopp', 'intense', 'avemnth', 'milint', 'econint', 'govmil',
       'govecon', 'oppmil', 'neutmil', 'neutecon'],
      dtype='object')

In [36]:


# get the unique conflict names in the 'conflict' column
conflict_names = df['conflict'].unique()

# create an empty list to store the results
results = []

# loop through the conflict names and append the corresponding ccode and country values to the results list
for conflict in conflict_names:
    conflict_df = df.loc[df['conflict'] == conflict]
    conflict_codes = conflict_df['ccode'].unique()
    countries = conflict_df['interven'].unique()
    ccode_str = ', '.join(str(c) for c in conflict_codes)
    country_str = ', '.join(str(c) for c in countries)
    results.append({'Conflict': conflict, 'CCodes': ccode_str, 'Countries': country_str})

# create a new dataframe from the results list and display it
results_df = pd.DataFrame(results)
results_df.head()
results_df.to_excel('../data_processed/conflict_code.xlsx')

In [39]:
import matplotlib.pyplot as plt


# group the dataframe by country and count the number of conflicts
country_counts = df.groupby('interven').nunique()['conflict']

# create a bar chart showing the number of conflicts for each country
country_counts.plot(kind='bar', figsize=(10, 5))

# set the chart title and axis labels
plt.title('Number of Conflicts by Country')
plt.xlabel('Country')
plt.ylabel('Number of Conflicts')

# show the chart
plt.show()

KeyError: 'thrdp'